### ISSUE TITLE
phpcbf uses wrong path on Windows (WSL)

### ISSUE THREAD

**Issue by jan-koch** [ahmadawais/VSCode-Tips-Tricks#1]
## Issue
When using the SaveAndRun command to automatically trigger phpcbf when saving a php file, the file path is not working due to forward slashes being omitted.

## Solution
Install the "[Save and Run with WSL](https://marketplace.visualstudio.com/items?itemName=raiscui.save-and-run-wsl)" extension by author "rascui" and extend the SaveAndRun command with the line `"wsl: true"` as follows:

```
"saveAndRun": {
        "commands": [
            {
                "match": "\\.php$",
                "cmd": "phpcbf -q --standard='WordPress' ${file}",
                "silent": true,
                "wsl": true
            }
        ]
    },

```

**Comment by AdelDima** [comment]
Thank you @jan-koch for the great help

**Comment by shivapoudel** [comment]
I had same problem when running in bash shell. Using single quotes did the trick and didn't switched to "[Save and Run with WSL](https://marketplace.visualstudio.com/items?itemName=raiscui.save-and-run-wsl)" :)

```json
	"saveAndRun": {
        "commands": [
            {
                "match": "\\.php$",
                "cmd": "phpcbf -q --standard='WordPress' '${file}'",
                "silent": true,
            }
        ]
    },
```

**Comment by jan-koch** [comment]
Can you post your config file here, so we can see the setup?  





On Wed, Dec 19, 2018 10:05 PM, Shiva Poudel notifications@github.com  wrote:
For me why it is not working :(



—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.



Best regards,Jan
Read the blogGet a quoteTwitter
