### ISSUE TITLE
HTML Tag Highlight (Lesson 24)

### ISSUE THREAD

**Issue by marcorieser** [ahmadawais/VSCode-Tips-Tricks#6]
All of the settings in the lesson 24 are deprecated and but the same result can be achieved with this settings
`"highlight-matching-tag.styles": {
        "opening": {
            "full": {
                "highlight": "rgba(165, 153, 233, 0.3)"
            }
        }
    }`

**Comment by ahmadawais** [comment]
@marcorieser thanks a lot for reporting. 

Fixed in this repo as well as here → https://github.com/ahmadawais/shades-of-purple-vscode#frequently-asked-questions

**Comment by ahmadawais** [comment]
From now on, I'll keep a label for changes.
